AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3.3
  SuggestExtensions: false
  NewCops: enable
Layout/MultilineMethodCallIndentation:
  Enabled: false
required:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
