# SPDX-FileCopyrightText: Copyright (c) 2018-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3.3
  SuggestExtensions: false
  NewCops: enable
Layout/MultilineMethodCallIndentation:
  Enabled: false
Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
Metrics/MethodLength:
  Max: 40
plugins:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
