docker:
  image: yegor256/rultor-image:1.19.0
assets:
  rubygems.yml: yegor256/home#assets/rubygems.yml
install: |-
  sudo gem install openssl -- --with-openssl-dir=/usr/local/rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/openssl
  pdd -f /dev/null
  sudo bundle install --no-color "--gemfile=$(pwd)/Gemfile"
release:
  script: |-
    bundle exec rake
    rm -rf *.gem
    sed -i "s/0\.0\.0/${tag}/g" backtrace.gemspec
    git add backtrace.gemspec
    git commit -m "Version set to ${tag}"
    gem build backtrace.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
merge:
  script: |-
    bundle exec rake
