readers:
  - "urn:github:526301"
assets:
  rubygems.yml: yegor256/home#assets/rubygems.yml
install: |-
  export GEM_HOME=~/.ruby
  export GEM_PATH=$GEM_HOME:$GEM_PATH
  bundle install
release:
  script: |-
    bundle exec rake
    rm -rf *.gem
    sed -i "s/0\.0\.0/${tag}/g" backtrace.gemspec
    git add backtrace.gemspec
    git commit -m "Version set to ${tag}"
    gem build backtrace.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
merge:
  script: |-
    bundle exec rake
deploy:
  script: |-
    echo "There is nothing to deploy"
    exit -1
